//------------------------------------------------------------------
//                   !!! WARNING !!! 
//
// This file is auto generated by ctrpp.exe utility from performance
// counters manifest:
//
// forward.man
//
// It should be regenerated every time the code is built.
// Do not check it in.
//-------------------------------------------------------------------

#pragma once

#define ForwardCounterSet1Guid { 0x5a74954, 0x8c0e, 0x4c42, 0x8b, 0x18, 0xc7, 0x43, 0xf, 0x5a, 0xd8, 0xc9 }

#define ForwardCounterSet1GuidString L"{05a74954-8c0e-4c42-8b18-c7430f5ad8c9}"

#define ForwardCounterSet1Name L"Forward Counter Set1"

#define ForwardRunningThread (1)
#define ForwardConnections (2)


