//------------------------------------------------------------------
//                   !!! WARNING !!! 
//
// This file is auto generated by ctrpp.exe utility from performance
// counters manifest:
//
// echo.man
//
// It should be regenerated every time the code is built.
// Do not check it in.
//-------------------------------------------------------------------

#pragma once

#define EchoCounterSet1Guid { 0xad216274, 0xab2a, 0x47dd, 0x8f, 0xf3, 0x45, 0x39, 0xef, 0x41, 0x27, 0xab }

#define EchoCounterSet1GuidString L"{ad216274-ab2a-47dd-8ff3-4539ef4127ab}"

#define EchoCounterSet1Name L"Echo Counter Set1"

#define EchoRunningThread (1)
#define EchoConnections (2)
#define EchoMemory (3)


